### ISSUE TITLE
Issue when having `from` in string

### ISSUE THREAD

**Issue by petobens** [tweekmonster/impsort.vim#10]
Consider the following `foo.py` file:

``` python
platform_statement = """SELECT platform
FROM mysql.ruby.applications
WHERE id = {app_id}
""".format(app_id=12)
```

When I run `:ImpSort` I get:

``` python
platform_statement = """SELECT platform
WHERE id = {app_id}
""".format(app_id=12)
```

i.e the `FROM` line gets deleted.  Thanks in advance for looking into this.

**Comment by tweekmonster** [comment]
I completely forgot about this.  I'll look into it in the morning.

**Comment by petobens** [comment]
Ok. There no is hurry. Thanks!!

**Comment by petobens** [comment]
Thank you!!

**Comment by tweekmonster** [comment]
No problem 👍

Quick question: your example above didn't work for me because it was uppercased.  The lowercased string did get matched, though.  Was the example a mistake?

**Comment by petobens** [comment]
Mmmm I believe  tried it exactly as I wrote it above (I'm pretty sure I originally wrote it uppercased since I generally write sql keywords uppercased).

**Comment by tweekmonster** [comment]
Well that's strange because I wasn't using case-insensitive patterns.  Do you have `'ignorecase'` enabled or something?

**Comment by petobens** [comment]
Yep, I use `set ignorecase` and `set smartcase`.

**Comment by tweekmonster** [comment]
Just tried it.  That's the dumbest thing I've ever seen.  That should only affect the user's `/` search.  Oh well, it's fixed.

**Comment by petobens** [comment]
Vim is full of surprises. Thanks once again. :)
