### ISSUE TITLE
impsort_start_nextline=1 is broken

### ISSUE THREAD

**Issue by DanCardin** [tweekmonster/impsort.vim#11]
I get 

> E15: Invalid expression: "\n".repeat(indent_text, indent).tail  
> E121: Undefined variable: tail

`
from asdfasdf import asdfasdf, ksjdlfgsdk, lkjolqierjkl, qwerasdljk, qwerqwer, alsdkjflktjmn, cmn`

Seems like the `impsort_start_nextline=1` is the cause

**Comment by tweekmonster** [comment]
Thanks!  Fix incoming.

**Comment by DanCardin** [comment]
Thanks for the super quick turnaround!
