### ISSUE TITLE
More impsort_start_nextline issues

### ISSUE THREAD

**Issue by DanCardin** [tweekmonster/impsort.vim#12]
with `impsort_start_nextline=1`, I get 

```
from asdfasdf import (
    alsdkjflktjmn, asdfasdf, cmn, ksjdlfgsdk, lkjolqierjkl, qwerasdljk,
                qwerqwer
)



def main(): pass
```

I would expect this

```
from asdfasdf import (
    alsdkjflktjmn, asdfasdf, cmn, ksjdlfgsdk, lkjolqierjkl, qwerasdljk,
    qwerqwer
)


def main(): pass
```

e.g. the hanging indent is more than the line before it (this isn't what I expected, but might be something you did on purpose. I wasn't sure), and the extra parenthesis line at the end seems to cause 3 lines after the import instead of 2.

**Comment by tweekmonster** [comment]
Huh, I didn't see that happen when I tested.  I'll check again.

**Comment by tweekmonster** [comment]
Never mind, I must've been remembering something else.  I think I see the problem.

**Comment by DanCardin** [comment]
It still leaves 3 blank lines after the import instead of the normal 2 (which is the case when it doesnt wrap)

**Comment by tweekmonster** [comment]
Ah, I wasn't testing with a def/class after the import.  I only saw two extra lines.  I'll take a look.

**Comment by DanCardin** [comment]
perfect!
