### ISSUE TITLE
Don't highlight when no imports

### ISSUE THREAD

**Issue by petobens** [tweekmonster/impsort.vim#14]
Consider the following GIF:
![aug-27-2016 17-56-54](https://cloud.githubusercontent.com/assets/2583971/18030048/e46ec3f6-6c7f-11e6-867c-b2ebb9c411c2.gif)

When there is an imported line variables are correctly highlighted. However with no imported lines variables are highlighted as Keyword (i.e red instead of white). Any chance of fixing this? Or is it a feature? Thanks!!

**Comment by tweekmonster** [comment]
It's because `imports.py` reads the whole file if no lines are fed into it (for testing).  A fix will be up soon.

**Comment by petobens** [comment]
Thank you!
