### ISSUE TITLE
Inconsistent grouping?

### ISSUE THREAD

**Issue by DanCardin** [tweekmonster/impsort.vim#15]
So starting with the imports:

```
import datetime
import dateutil
import flask
```

I get 

```
import datetime

import dateutil

import flask

```

Which I'm not sure what's up with that. All three should be 3rd party libs which get grouped together. (plus in getting together this example, I noticed imports by themselves in a file adds an unnecessary newline at the EOF)

Secondarily

```
from sqlalchemy import and_, not_, or_
from sqlalchemy.orm import aliased

from myapi import db
from myapi.subpackage import models
```

Correctly sorts by, by doing nothing (including no newline at the EOF), but

```
from sqlalchemy import and_, not_, or_
from sqlalchemy.orm import aliased

from myapi import db
```

sorts to (again, newline EOF)

```
from myapi import db

from sqlalchemy import and_, not_, or_
from sqlalchemy.orm import aliased

```

**Comment by tweekmonster** [comment]
Not sure what's up with your first example.  This is what I get when I sort them:

``` python
import datetime

import flask
import dateutil
```

Which looks correct to me.  `datetime` is a builtin.  The other two are third party, but orphans/loners so are grouped together.

So, your main issue is that scripts that only contain imports shouldn't have a blank line at the end of the file?  I think I can fix that easily.

**Comment by DanCardin** [comment]
Woops, no idea why I said datetime was a third party lib, but it looks like dateutil was an issue with my virtualenv or something because a fresh env fixed it. weird!
