### ISSUE TITLE
Disappearing variable line after multiple import lines

### ISSUE THREAD

**Issue by petobens** [tweekmonster/impsort.vim#19]
Hi @tweekmonster. If I run `ImpSort` on the following code:

```python
import pandas as pd
from foo import (baaaaaaaaaaaaaaaaaarz, baaaaaaaaaaaaaaz,
                 foooooooooooooooooasdasdasdas)
z = 3
```
I get

```python
import pandas as pd

from foo import (baaaaaaaaaaaaaaaaaarz, baaaaaaaaaaaaaaz,
                 foooooooooooooooooasdasdasdas)
```
Is this expected? Thanks!

**Comment by tweekmonster** [comment]
> Is this expected?

Well, yes of course!  Case closed! 😜

I'll take a look at this in the morning.  Does this still happen with a space between the lines?

**Comment by petobens** [comment]
Yes, it happens with any number of spaces between the multilline import and the variable assignment.

**Comment by petobens** [comment]
Thank you!
