### ISSUE TITLE
Order of imported items is changed?

### ISSUE THREAD

**Issue by beaugunderson** [tweekmonster/impsort.vim#2]
`from django.contrib.auth.models import AbstractUser, UserManager`

becomes

`from django.contrib.auth.models import UserManager, AbstractUser`

**Comment by tweekmonster** [comment]
This is the same issue as with #3, except using the `g:impsort_method_imports` option.

**Comment by tweekmonster** [comment]
I forgot to clarify that the you're right that the sort order is wrong.  It was one of those moments where I subconsciously retyped a line above.  I also misspelled the variable name 😱

**Comment by beaugunderson** [comment]
thanks for the quick fix!
