### ISSUE TITLE
Error detected while processing function impsort#highlight_imported[1]..<SNR>109_init:

### ISSUE THREAD

**Issue by hanspinckaers** [tweekmonster/impsort.vim#27]
Hi,

Thanks for your lovely plugin. I encountered the following problem:
```
Error detected while processing function impsort#highlight_imported[1]..<SNR>109_init:
line   12:
E461: Illegal variable name: Fatal Python error: Py_Initialize: can't initialize sys standard stream
```

Commenting out the following line in autoload/impsort.vim removes the error:
```
function! impsort#highlight_imported(force) abort
"  call s:init()
```

Edit: I have to add: the plugin still works after this.

**Comment by tweekmonster** [comment]
This has been addressed by handling the error and printing it once.  However, it looks like that error is generated due to something either being broken in the builtin modules or your code shadowed a builtin module.
