### ISSUE TITLE
Combines different imports lines into one

### ISSUE THREAD

**Issue by sureshvv** [tweekmonster/impsort.vim#29]
If I have:

    from . import patches  # noqa: E401
  
    from . import (
      blackout,
      utils1,
      utils2,
      utils3,
      utils4,
      utils6,
   )

it combines the two and messes up the inline comment

**Comment by sureshvv** [comment]
Worked around this by changing the file to

`
from patches import <variable>  # noqa: E401
`

**Comment by tweekmonster** [comment]
This has been fixed so that your example would sort this way:

```python
from . import blackout, utils1, utils2, utils3, utils4, utils6
from . import patches  # noqa: E401
```
