### ISSUE TITLE
Non-sensical sort order

### ISSUE THREAD

**Issue by beaugunderson** [tweekmonster/impsort.vim#3]
![screenshot](https://i.imgur.com/gxwrs7i.png)
- the two `django.db` lines should be together
- `oauth2_provider` is moved before `django`
- `contrib.staticfiles` should come after `contrib.auth.models`

**Comment by tweekmonster** [comment]
This is due to the default sort order preferring to sort by length.  I guess I didn't test for module depth with similar prefixes.  I'll have to see if I can make depth/length be preferred while keeping similar prefixes together.

If you want to prioritize alphabetic sorting, see if this works for you:

``` vim
let b:impsort_method_module = ['alpha', 'depth', 'length']
```

It's using the buffer variable so you can try it at run time.

**Comment by tweekmonster** [comment]
I've updated it so that it takes the longest common prefix into account.  I didn't reference this issue correctly, but it's fixed in e708f89060a5ab86f385eb8cb6696eb25c40b56c

You should be able to use the default sorting method with the prefix grouping.  Let me know what you think.

**Comment by beaugunderson** [comment]
closer!

![screenshot](https://i.imgur.com/9fwqI3b.png)

seems to prematurely switch to `()`-style imports now? (those would fit in 79 columns)

**Comment by tweekmonster** [comment]
What is `'textwidth'` set to?  That's not happening for me.

Edit: Also, if you post more findings, would you mind including the text version so I can test a little faster 😉

**Comment by tweekmonster** [comment]
Quick update, I have to set `textwidth` to 40 to see the results you're seeing.

**Comment by beaugunderson** [comment]
weird, tried again and i no longer see the behavior!

**Comment by tweekmonster** [comment]
@beaugunderson Cool.  I'm going to close this issue since it seems to be resolved.  Definitely update this issue if you find out what happened.
