### ISSUE TITLE
Invalid channel ID

### ISSUE THREAD

**Issue by CalSch** [tweekmonster/impsort.vim#35]
Whenever I do something in my file like save or undo, I get this error:
```
Error detected while processing function impsort#highlight_imported[17]..<SNR>95
_do_async_job:
line   17:
E900: Invalid channel id
```
Here are my imports:
```py
import time,math
```

**Comment by tweekmonster** [comment]
This is most likely the subprocess exiting prematurely, which can be for various reasons, but the most likely reason is that `python` is the wrong version. There won't be further updates to this plugin, but if you still happen to have this problem, you'd reveal more about the problem by running the script directly:

```sh
python bin/import.py some_script.py </dev/null
```
