### ISSUE TITLE
Attributes are highlighted as imported if it matches import names

### ISSUE THREAD

**Issue by tweekmonster** [tweekmonster/impsort.vim#7]
Example:

![](https://cloud.githubusercontent.com/assets/2583971/16465989/cb160be4-3e17-11e6-80f4-62f06a982621.png)

@petobens

**Comment by petobens** [comment]
With your recent commit  the issue es partially fixed:
![jun-30-2016 15-25-01](https://cloud.githubusercontent.com/assets/2583971/16499440/e4fae90c-3ed6-11e6-9106-a5affc14e223.gif)

For some reason when using `from time import time`, the `time` module (i.e the first `time`) is highlighted as a function.
Also I don't know why `start` is highlighted as a module.
Thanks!!!

**Comment by tweekmonster** [comment]
It should be fixed now.  I also made it so that `from time import time` won't highlight the imported name in the first part of the line.

**Comment by petobens** [comment]
Thank you!
