### ISSUE TITLE
Issues when folding a function

### ISSUE THREAD

**Issue by petobens** [tweekmonster/impsort.vim#9]
I use [this plugin](https://github.com/tmhedberg/SimpylFold) to fold my python classes, functions and imports. However there seems to be a clash with Impsort. Consider the following `.py` file:

``` python
def bar():
    print('bar')
    import sys
    sys.exit()
```

As in the GIF, fold this function and then run `:ImpSort`. You will see that the whole function disappears. Thanks in advance for looking into this!

![jul-13-2016 11-11-41](https://cloud.githubusercontent.com/assets/2583971/16806372/a2d56494-48ea-11e6-88f7-6ae7de7ca0b6.gif)

**Comment by petobens** [comment]
When using the following two functions:

``` python
def foo():
    import sys
    sys.exit()
    print('foo')


def bar():
    print('bar')
    import sys
    sys.exit()
```

and repeating the above procedure I get (as in the GIF)

``` python
    import sys
    import sys
```

![jul-13-2016 11-16-02](https://cloud.githubusercontent.com/assets/2583971/16806582/6bfaa776-48eb-11e6-8208-807b8c86668d.gif)

**Comment by tweekmonster** [comment]
I know what's going on.  The plugin uses a range of lines with the `delete` command.  I think the range is based on lines that you see, not the actual line numbers.  I'll see if there's a better way to go about it.

**Comment by petobens** [comment]
Awesome. Thanks!!

**Comment by tweekmonster** [comment]
I think it's fixed now.  Let me know if you're still having problems with folds.

**Comment by petobens** [comment]
Seems to work great. Thank you!
